### ISSUE TITLE
Can't run tred.py: multiple exceptions

### ISSUE THREAD

**Issue by jbsysadmin** [humanlongevity/tredparse#2]
Given Centos 6.x,  Python 2.7.7 installed to custom NFS directory,  tred.py, and a correctly-formatted CVS file, an end-user gets these errors:

ERROR:tredparse.tred:Exception on `/<path_to_data1>/data1.bam` DM1 (__init__() got an unexpected keyword argument 'mismatch')
ERROR:tredparse.tred:Exception on `/<path_to_data1>/data2.bam` HD (__init__() got an unexpected keyword argument 'mismatch')
 
We also have Python 3.6.1, but I don't believe your tredparse item works for that. Do you have any leads on this type of error?

Regards,
W. John Burns

**Comment by tanghaibao** [comment]
@jbsysadmin 

John, sorry for a slow response. I have not seen these errors before. Did the test data work for you, per the `README`? For example, in the project folder, does this work?

```bash
./tred.py tests/samples.csv --workdir work
```

Haibao

**Comment by jbsysadmin** [comment]
Haibao:

This time, I apologize for delay. The build machine I use failed, and there was a flood of priority tasks before I had a free minute to respond.

Here is the representative failure. I ran this as the user reporting the issue just now.
$ python /nfs/<path>/python2.7.7/bin/tred.py /home/<username>/samples.csv --workdir /home/<username>/try/
ERROR:tredparse.tred:Exception on `/home/<username>/selfinstall/tredparsebk/tests/t002.bam` DM1 (__init__() got an unexpected keyword argument 'mismatch')
ERROR:tredparse.tred:Exception on `/home/<username>/selfinstall/tredparsebk/tests/t001.bam` HD (__init__() got an unexpected keyword argument 'mismatch')
{
    "bam": "/home/<username>/selfinstall/tredparsebk/tests/t001.bam",
    "samplekey": "t001",
    "tredCalls": {
        "depthY": -1,
        "inferredGender": "Unknown",
        "readLen": 150
    }
}
{
    "bam": "/home/<username>/selfinstall/tredparsebk/tests/t002.bam",
    "samplekey": "t002",
    "tredCalls": {
        "depthY": -1,
        "inferredGender": "Unknown",
        "readLen": 150
    }
}
Elapsed time=0:00:00.607545

**Comment by tanghaibao** [comment]
@jbsysadmin 
It seems likely that there is another `ssw` library on your `PYTHONPATH` that the software calls which did not match the alignment function parameters. Can you set up a clean environment using `virtualenv` and try re-installing `tredparse` from there?

Haibao

**Comment by jbsysadmin** [comment]
Haibo:

It seems this was it! I didn’t notice the end-user PYTHONPATH. Unsetting allowed the items to run, free from the ssw you cited.
Thank you for your help.

One thing: will this be available on Python3 ? I ask in case there is ever a move to standardize to a newer Python...

-John

**Comment by tanghaibao** [comment]
@jbsysadmin 
I'm glad that it works now. We don't yet have a py3-compatible version at this point but I'll provide an update once that's done.

Haibao
